### ISSUE TITLE
Wanna merge with awesome-aurelia?

### ISSUE THREAD

**Issue by riddla** [ostyn/aurelia-resources#2]
Maybe we can merge the two collections within https://github.com/riddla/awesome-aurelia? So we can later benefit from being listed over at https://github.com/sindresorhus/awesome/blob/master/readme.md?

**Comment by ostyn** [comment]
I'm cool with that. What's the easiest way for me to get that over? Is it alright if I submit them as one PR?

**Comment by riddla** [comment]
A PR would be great, thank you!

**Comment by ostyn** [comment]
Done. And I'll definitely remain active in the new one. Cheers!

**Comment by riddla** [comment]
Merged and done :) Lookig forward to your contributions.
